spring:
  application:
    name: golive-id-generate-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #访问主库
    url: jdbc:mysql://xxx.xxx.xxx.xxx:8808/golive_common?useUnicode=true&characterEncoding=utf8
    username: xxx
    password: xxx

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://xxx.xxx.xxx.xxx:8848?namespace=golive-test&&username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: 9092