spring:
  application:
    name: golive-im-router-provider
  data:
    redis:
      port: 8801
      host: xxx.xxx.xxx.xxx
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10
golive:
  rmq:
    producer:
      nameSrv: xxx.xxx.xxx.xxx:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://xxx.xxx.xxx.xxx:8848?namespace=golive-test&&username=nacos&&password=nacos
  protocol:
    port: 9098
