version: '3'
services:
  golive-api-docker-1:
    container_name: golive-api-docker-1
    image: 'golive-api-docker'
    ports:
      - "8081:8081"
    volumes:
      - /tmp/logs/golive-api:/tmp/logs/golive-api
    environment:
      - spring.cloud.nacos.discovery.ip=xxx.xxx.xxx.xxx
      - TZ=Asia/Shanghai
      - server.port=8081
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k

  golive-api-docker-2:
    container_name: golive-api-docker-2
    image: 'golive-api-docker'
    ports:
      - "8082:8082"
    volumes:
      - /tmp/logs/golive-api:/tmp/logs/golive-api
    environment:
      - spring.cloud.nacos.discovery.ip=xxx.xxx.xxx.xxx
      - TZ=Asia/Shanghai
      - server.port=8082
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k