spring:
  application:
    name: golive-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:golive-db-sharding.yaml
    hikari:
      pool-name: golive-user-pool
      minimum-idle: 15
      maximum-pool-size: 300
      connection-timeout: 4000
      max-lifetime: 60000
  data:
    redis:
      # Redis服务器连接端口
      port: 6379
      # Redis服务器地址
      host: 127.0.0.1
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 10
          # 连接池最大连接数
          max-active: 50
          # 连接池最大空闲连接
          max-idle: 20
golive:
  rmq:
    producer:
      nameSrv: 39.101.202.169:9876
      groupName: ${spring.application.name}
      retryTimes: 3
      sendTimeOut: 60000
    consumer:
      nameSrv: 39.101.202.169:9876
      groupName: ${spring.application.name}

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://39.101.202.169:8848?namespace=golive-test&&username=nacos&&password=nacos
  server: true
  protocol:
    name: dubbo
    port: 9091
