version: '3'
services:
  golive-user-provider-docker-1:
    container_name: golive-user-provider-docker-1
    image: 'golive-user-provider-docker'
    ports:
      - "9091:9091"
    volumes:
      - /tmp/logs/golive-user-provider:/tmp/logs/golive-user-provider
    #注意 xss参数是设置线程的栈空间大小，这里至少要比136k大，否则会出错
    environment:
      - TZ=Asia/Shanghai
      - DUBBO_IP_TO_REGISTRY=39.101.202.169
      - DUBBO_PORT_TO_REGISTRY=9091
      - DUBBO_PORT_TO_BIND=9091
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k

  golive-user-provider-docker-2:
    container_name: golive-user-provider-docker-2
    image: 'golive-user-provider-docker'
    ports:
      - "9092:9092"
    volumes:
      - /tmp/logs/golive-user-provider:/tmp/logs/golive-user-provider
    #注意 xss参数是设置线程的栈空间大小，这里至少要比136k大，否则会出错
    environment:
      - TZ=Asia/Shanghai
      - DUBBO_IP_TO_REGISTRY=39.101.202.169
      - DUBBO_PORT_TO_REGISTRY=9092
      - DUBBO_PORT_TO_BIND=9092
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k