spring:
  application:
    name: qiyu-live-id-generate-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #访问主库
    url: jdbc:mysql://39.101.202.169:8808/golive_common?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://39.101.202.169:8848?namespace=golive-test&&username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: 9098